Add boost. Add junit report

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -23,7 +23,7 @@ jobs:
     - uses: actions/checkout@v3
 
     - name: Install dependencies
-      run: sudo apt update && sudo apt install libxerces-c-dev libsundials-dev libginac-dev libhdf5-dev libismrmrd-dev mpi-default-bin
+      run: sudo apt update && sudo apt install libxerces-c-dev libsundials-dev libginac-dev libhdf5-dev libismrmrd-dev mpi-default-bin libboost-all-dev
 
 
     - name: Configure CMake
@@ -40,5 +40,11 @@ jobs:
       #run: chmod u+x ./sanityck && ./sanityck ../share/examples 2
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}}
+      run: ctest -C ${{env.BUILD_TYPE}} --output-junit test.xml
+    
+    - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './test.xml'
 
